name: Setup
description: Setup Node and install dependencies

inputs:
  node_version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'

    - name: Setup Yarn
      run: corepack enable && corepack prepare yarn@3.2.3 --activate
      shell: bash

    - name: Install
      run: yarn --version && yarn install --immutable
      shell: bash
