# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  node_version: 18.10.x

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.node_version }}
      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v3
      - name: Lint
        run: yarn nx affected --target=lint --parallel=3
      - name: Check Style
        run: yarn nx affected --target=formatDry --parallel=3
      - name: Check Types
        run: yarn nx affected --target=ts --parallel=3
      - name: Test
        run: yarn nx affected --target=testCoverage --parallel=3
      - name: Merge Coverage reports
        run: yarn tsm ./tools/coverageMerger.mts
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          fail_ci_if_error: false
          verbose: true
  e2e:
    name: E2E Tests
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
        os: [macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.node_version }}
      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v3
      - name: Run in ${{ matrix.browser }} [${{ matrix.os }}]
        run: yarn nx affected --target=e2e
        env:
          OS: ${{ matrix.os }}
          BROWSER: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
          path: ./e2e
          retention-days: 1
