# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Check

on:
  pull_request:
    branches: [main]

env:
  node_version: 18.10.0

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.node_version }}
      - name: NX Set SHAs
        uses: nrwl/nx-set-shas@v2
      - name: Lint
        run: yarn nx affected --target=lint --parallel=3
      - name: Check Style
        run: yarn nx affected --target=formatDry --parallel=3
      - name: Check Types
        run: yarn nx affected --target=ts --parallel=3
      - name: Test
        run: yarn nx affected --target=testCoverage --parallel=3
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
